import React from "react";
import "../styles/global.css";

/**
 * A simple, unauthenticated page to display the Privacy Policy.
 * It's styled to be clean, readable, and theme-aware, matching TermsPage.jsx.
 */
export default function PrivacyPage() {
  return (
    <div className="legal-page-container">
      <div className="legal-page-content">
        <span className="legal-page-eyebrow">Mataasnakahoy BPLO</span>
        <h1>Privacy Policy for REVELA</h1>
        <div className="legal-page-divider" />
        <p className="legal-page-subtitle">Last Updated: October 26, 2023</p>

        <p>
          This Privacy Policy describes how the Municipality of Mataasnakahoy
          ("we," "us," or "our") collects, uses, and protects information in
          connection with your use of the REVELA geospatial intelligence and
          field inspection platform, including the REVELA web dashboard ("Web
          Portal") and the REVELA mobile application ("Mobile App").
        </p>

        <div className="legal-page-notice">
          <p>
            This policy applies only to authorized municipal personnel who use
            the REVELA platform. It does not apply to the general public.
          </p>
        </div>

        <h2>1. Information We Collect</h2>
        <p>
          We collect several types of information to provide and improve the
          Service:
        </p>
        <ul>
          <li>
            <strong>Personal Account Information:</strong> When you are granted
            an account, we collect your full name, email address, and assigned
            role (e.g., "Admin," "Inspector"). We store your password in a
            secure, hashed format. If you enable two-factor authentication
            (2FA), we store the necessary secret key to verify your identity.
          </li>
          <li>
            <strong>Field Inspection Data (from Mobile App):</strong> When
            Inspectors use the Mobile App, we collect data submitted in field
            reports, which includes:
            <ul>
              <li>Photographic evidence of establishments.</li>
              <li>Notes, remarks, and inspection results.</li>
              <li>
                The precise GPS coordinates (latitude and longitude) where the
                report is submitted.
              </li>
            </ul>
          </li>
          <li>
            <strong>Business Registry Data (from Web Portal):</strong> When
            Administrators upload business registry files (e.g., CSV, Excel),
            we process the information contained within, which may include
            business names, addresses, owner details, and permit statuses.
          </li>
          <li>
            <strong>Geospatial & Usage Data:</strong> We automatically collect
            information about your interaction with the Service. This includes:
            <ul>
              <li>
                Data generated by the system, such as geocoded addresses from
                the Google Maps API and the location of automatically detected
                businesses.
              </li>
              <li>
                System logs, IP addresses, and actions taken within the
                platform for security auditing and system maintenance.
              </li>
            </ul>
          </li>
        </ul>

        <h2>2. How We Use Your Information</h2>
        <p>
          We use the information we collect for the following official
          purposes:
        </p>
        <ul>
          <li>
            <strong>To Provide and Secure the Service:</strong> To authenticate
            users, enforce role-based access controls, and monitor for security
            threats.
          </li>
          <li>
            <strong>To Facilitate Municipal Operations:</strong> To manage the
            business registry, assign and track inspection tasks, visualize
            compliance on a map, and generate reports.
          </li>
          <li>
            <strong>For Geospatial Analysis:</strong> To run automated detection
            of unregistered businesses, identify compliance hotspots, and
            prescribe enforcement priorities.
          </li>
          <li>
            <strong>To Communicate with You:</strong> To send system
            notifications, alerts for new assignments, and facilitate password
            reset requests.
          </li>
        </ul>

        <h2>3. Data Sharing and Disclosure</h2>
        <p>
          Your information is treated as confidential and is used for internal
          municipal purposes only. We do not sell your personal information. We
          may disclose information under the following limited circumstances:
        </p>
        <ul>
          <li>
            <strong>Third-Party Services:</strong> We use the Google Maps API
            for geocoding and mapping. Address data may be sent to Google for
            this purpose and is subject to Google's Privacy Policy.
          </li>
          <li>
            <strong>Legal Requirements:</strong> We may disclose your
            information if required to do so by law or in response to valid
            requests by public authorities.
          </li>
        </ul>

        <h2>4. Data Security</h2>
        <p>
          We implement a variety of security measures to maintain the safety of
          your personal information. These include password hashing, two-factor
          authentication, role-based access controls, and secure data
          transmission protocols. However, no method of transmission over the
          Internet or method of electronic storage is 100% secure.
        </p>

        <h2>5. Data Retention</h2>
        <p>
          We retain your account information and the data you generate for as
          long as you are an active user and as necessary to fulfill the
          purposes outlined in this policy, or as required for official
          municipal record-keeping and legal obligations.
        </p>

        <div className="legal-page-footer">
          Powered by <strong>REVELA</strong>
          <br />
          &copy; 2026 Municipality of Mataasnakahoy — Business Permits and
          Licensing Office (BPLO). All rights reserved.
        </div>
      </div>
    </div>
  );
}